# Generated by Django 5.2.3 on 2026-08-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_create_existing_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
