# Generated by Django 5.2.3 on 2026-08-25 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_attendance_marked_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='unique_slot_session_date',
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('timetable_slot', 'session_date'), name='unique_open_slot_session_date'),
        ),
    ]
