# Generated by Django 5.2.3 on 2026-08-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_remove_attendancesession_unique_slot_session_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
